#!/bin/sh
cat SafeMathLib.sol > MyMasterCombined.sol
cat Ownable.sol >> MyMasterCombined.sol
cat ERC20Basic.sol >> MyMasterCombined.sol
cat ERC20.sol >> MyMasterCombined.sol
cat FractionalERC20.sol >> MyMasterCombined.sol
cat StandardToken.sol >> MyMasterCombined.sol
cat UpgradeAgent.sol >> MyMasterCombined.sol
cat UpgradeableToken.sol >> MyMasterCombined.sol
cat ReleasableToken.sol >> MyMasterCombined.sol
cat MintableToken.sol >> MyMasterCombined.sol
cat CrowdsaleToken.sol >> MyMasterCombined.sol
cat FinalizeAgent.sol >> MyMasterCombined.sol
cat PricingStrategy.sol >> MyMasterCombined.sol
cat Haltable.sol >> MyMasterCombined.sol
cat Crowdsale.sol >> MyMasterCombined.sol
cat BonusFinalizeAgent.sol >> MyMasterCombined.sol
cat MintedEthCappedCrowdsale.sol >> MyMasterCombined.sol
cat EthTranchePricing.sol >> MyMasterCombined.sol
